version: "3.8"
services:
  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test_password
      MONGO_INITDB_DATABASE: admin
    network_mode: "host"
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
